apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/MartinBasti/paketo-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: test-prefetch-permissions
    appstudio.openshift.io/component: paketo-container-ta
    pipelines.appstudio.openshift.io/type: build
  name: paketo-container-ta-on-push
  namespace: mbasti-tenant
spec:
  params:
    - name: dockerfile
      value: Containerfile
    - name: git-url
      value: '{{source_url}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/mbasti-tenant/paketo-container-ta:{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: prefetch-input
      value: |
        [{"type": "gomod", "path": "toml"},
         {"type": "gomod", "path": "jam"},
         {"type": "gomod", "path": "create-package"},
         {"type": "gomod", "path": "cosign"},
         {"type": "gomod", "path": "syft"},
         {"type": "gomod", "path": "pack"},
         {"type": "rpm", "path": "."}]
    - name: hermetic
      value: "true"
    - name: dev-package-managers
      value: "true"
    - name: enableSymlinkCheck
      value: "false"
    - name: cachi2-log-level
      value: "debug"
    - name: build-image-index
      value: "false"
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
